### ISSUE TITLE
Sugestão: Listar as Startups no README

### ISSUE THREAD

**Issue by braulio94** [BukaApp/startups-from-angola#4]
Boas devs @codder404 & @JovanyNegocio 
Gosto de que estão a fazer e gostaria de apoiar sugerindo o seguinte.
Listar as startups no README de modo a facilitar a contribuição no repositorio pra quem não programa em Javascript. No final apresentar esta mesma lista na pagina.

**Comment by JovanyNegocio** [comment]
Done, o @DCCOsTA7 adicionou uma lista das startups no README.
