### ISSUE TITLE
Sugestão: Dividir por categoria

### ISSUE THREAD

**Issue by braulio94** [BukaApp/startups-from-angola#5]
Devs @JovanyNegocio e @codder404 
Importante dividir as lista em categorias pra facilitar o leitor achar a startup que procura.

**Comment by JovanyNegocio** [comment]
@braulio94 exacto, essa é ideia mesmo.

**Comment by efeeseao** [comment]
Vai ser feito desse jeito

**Comment by JovanyNegocio** [comment]
Done!
